// Conformance vectors: byte-exact golden files under vectors/
// (generated by svb-cli/0.2.1 — see vectors/README.md)
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';
import { encode } from '../src/encoder.js';
import { decode } from '../src/decoder.js';
import { validate } from '../src/validate.js';

const HERE = join(dirname(fileURLToPath(import.meta.url)), '..', 'vectors');
const DEFLATE = (u8) => zlib.deflateRawSync(u8, { level: 9 });
const INFLATE = (u8) => zlib.inflateRawSync(u8);
const OPTS = { scale: 64, generator: 'svb-cli/0.2.1', deflate: DEFLATE };

const CASES = [
  ['v01-icon', ['<title>Map pin</title>', '#e63946']],
  ['v02-gradient', ['linearGradient', 'url(#svbg0)', '#e63946', '#457b9d']],
  ['v03-negative', ['#12b886', '#f08c00']],
  ['v04-template', ['#7048e8']],
];

test('vectors: encode(source) is byte-exact against the golden files', () => {
  for (const [name] of CASES) {
    const src = readFileSync(join(HERE, 'src', `${name}.svg`), 'utf8');
    const golden = readFileSync(join(HERE, `${name}.svb`));
    const { bytes } = encode(src, OPTS);
    assert.ok(Buffer.from(bytes).equals(golden), `${name}: re-encoding diverges from the golden vector`);
  }
});

test('vectors: golden files decode with the expected content', () => {
  for (const [name, markers] of CASES) {
    const golden = readFileSync(join(HERE, `${name}.svb`));
    const { svg, meta } = decode(golden, { inflate: INFLATE });
    assert.ok(!svg.includes('//>'), `${name}: malformed XML`);
    for (const m of markers) assert.ok(svg.includes(m), `${name}: missing "${m}" in decoded output`);
    assert.ok(meta.elements > 0, `${name}: no elements`);
  }
});

test('vectors: golden files pass every structural validation check', () => {
  for (const [name] of CASES) {
    const report = validate(readFileSync(join(HERE, `${name}.svb`)), { inflate: INFLATE });
    // V-11/V-12 are accessibility (name/description) — vectors without titles
    // legitimately miss them; structural failures would mean broken goldens
    const structural = report.checks.filter((c) => !c.pass && c.id !== 'V-11' && c.id !== 'V-12');
    assert.deepEqual(structural, [], `${name}: structural validation failures`);
  }
});

test('vectors: v04 uses DEF templates', () => {
  const src = readFileSync(join(HERE, 'src', 'v04-template.svg'), 'utf8');
  const { stats } = encode(src, OPTS);
  assert.ok(stats.templates >= 1, 'expected at least one DEF template');
});
